# gateway configuration
#version: 2
#daemon: true
error_log: true
#pid_file: "path to process id file"
#upgrade_sock: "path to upgrade socket"
#user: "user"
#group: "group"
#threads: 10
#work_stealing: true
#ca_file: "path to ca file"
#grace_period_seconds: 10
#graceful_shutdown_timeout: 10
#client_bind_to_ipv4:
#  - "address"
#  - "address"
#client_bind_to_ipv6:
#  - "address"
#  - "address"
#upstream_keepalive_pool_size: 1000
#upstream_connect_offload_threadpools: 100
#upstream_connect_offload_thread_per_pool: 100
#upstream_debug_ssl_keylog: true

clusters:
  - name: test-service
    host: "localhost"
    tls: false
#    discovery:
#      consul:
#        name: "test-service"
#        passing: true
#    rate_limit:
#      global:
#        basic:
#          limit: 100
#      client:
#        basic:
#          limit: 100
    prefix: "/service"
#    cache:
#      memory:
#        cache_ttl: 10
#        max_size: 5
#        max_cache: 10
#        lock_timeout: 5000
#    retry: 3
#    timeout: 2000
    auth:
#      key:
#        allowed:
#          - "secret"
#          - "key1"
#     jwt:
#       secret: "your-secret-key"
    consumers:
      - name: "user"
        acl:
          - "acl1"
          - "acl2"
    upstream:
      - "localhost:8000"
      - "localhost:8001"
    routes:
      - name: "view-only-acl"
        paths:
          - "/product"
          - "/order"
          - "/api"
        methods:
          - GET
          - POST
        consumers:
          - name: "user"
            acl:
              - "view-product"
              - "view-order"

  - name: auth
    host: "localhost"
    tls: false
    prefix: "/jwt"
#    rate_limit:
#      basic:
#        limit: 100
#    retry: 3
#    timeout: 2000
    request:
      headers:
        remove:
          - key: "server-name"
    response:
      headers:
        insert:
          - key: "Test-KEY"
            value: "some value"
          - key: "Test-KEY-2"
            value: "some value 2"
        remove:
          - key: "X-Custom-Header"
    upstream:
      - "localhost:8080"

  - name: test-auth
    host: "localhost"
    tls: false
    prefix: "/auth-test"
    upstream:
      - "localhost:8000"
      - "localhost:8001"
    routes:
      - name: "validation"
        paths:
          - "/tes"
          - "/idk"

consumers:
  - name: "admin"
    acl:
      - "edit-product"
      - "delete-product"
  - name: "user"
    acl:
      - "acl1"
      - "search-product"
