[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
parking_lot = "0.12"
crossbeam-queue = "0.3"
thread_local = "1.1"
lru = "0.12.5"
ahash = "0.8.11"
